### ISSUE TITLE
Unmet peer dependency "lodash@>=4.0".

### ISSUE THREAD

**Issue by CobyPear** [cupcakearmy/svelte-cloudinary#11]
When building an app with `svelte-cloudniary` on Vercel. I receive the following warning: 

`warning "svelte-cloudinary > cloudinary-core@2.12.0" has unmet peer dependency "lodash@>=4.0".`

The build then fails trying to resolve lodash:

```
> Using @sveltejs/adapter-vercel
--
08:52:04.659 | Error: Cannot find module 'lodash/assign'
08:52:04.659 | Require stack:
08:52:04.659 | - /vercel/path0/node_modules/cloudinary-core/cloudinary-core.js
08:52:04.659 | - /vercel/path0/node_modules/svelte-cloudinary/dist/index.js
08:52:04.660 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
08:52:04.660 | at Function.Module._load (internal/modules/cjs/loader.js:746:27)
08:52:04.660 | at Module.require (internal/modules/cjs/loader.js:974:19)
08:52:04.660 | at require (internal/modules/cjs/helpers.js:93:18)
08:52:04.660 | at webpackUniversalModuleDefinition (/vercel/path0/node_modules/cloudinary-core/cloudinary-core.js:10:28)
08:52:04.660 | at Object.<anonymous> (/vercel/path0/node_modules/cloudinary-core/cloudinary-core.js:17:3)
08:52:04.661 | at Module._compile (internal/modules/cjs/loader.js:1085:14)
08:52:04.661 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
08:52:04.661 | at Module.load (internal/modules/cjs/loader.js:950:32)
08:52:04.661 | at Function.Module._load (internal/modules/cjs/loader.js:790:12)
08:52:04.661 | Error: Cannot find module 'lodash/assign'
08:52:04.662 | Require stack:
08:52:04.662 | - /vercel/path0/node_modules/cloudinary-core/cloudinary-core.js
08:52:04.662 | - /vercel/path0/node_modules/svelte-cloudinary/dist/index.js
08:52:04.663 | > 500 /
08:52:04.664 | Error: 500 /
08:52:04.664 | at file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index5.js:167:11
08:52:04.664 | at visit (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index5.js:326:5)
08:52:04.692 | error Command failed with exit code 1.
08:52:04.692 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
08:52:04.703 | Error: Command "yarn run build" exited with 1
```
Willing to spend some time on this today but I wanted to open an issue in case it's just me :)

**Comment by cupcakearmy** [comment]
Damn, will need to add it back in, I tought the core sdk had integrated it. Will do, thanks for reporting!
